import type { Metadata } from "next";
import localFont from "next/font/local";
import { Theme, ThemePanel } from '@radix-ui/themes';
import "./globals.css";
import '@radix-ui/themes/styles.css';
import NavBar from "./(components)/nav-bar";
import "@radix-ui/themes/layout.css";
import ClientRootLayout from "./(components)/client-root-layout";


const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <Theme>
                    {children}
                </Theme>
            </body>
        </html>
    );
}